Test form
Israel-Laguan/theia-testing-app pull request #2
Opened 2023-05-19 17:36 UTC by Allislove

2023-05-19 18:02 UTC, Israel-Laguan requested changes

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/loader.tsx
> +export const Loader = () => {
Remove extra lines

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +      // console.log("File updated", file.name);
Remove this line

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +      console.log(loading, '*** 01 Loading ***')
Remove

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +          // console.log(jsonData, "JSON DATA ***");
Remove

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +          //console.log("Hello World!");
Remove

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +              notify('Cargado de manera satisfactoria')
Please use English

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +          // setLoading(false);
Remove if not needed

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +    // console.log(data);
Remove

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +    // console.log("JSON cargado de manera satisfactoria");
Remove

2023-05-19 18:02 UTC, Israel-Laguan commented on src/components/questions.tsx
> +    // console.log("Error al cargar el JSON");
Remove

2023-05-19 18:02 UTC, Israel-Laguan commented on src/pages/exam.tsx
> +  return(
Remove extra lines

2023-05-19 18:02 UTC, Israel-Laguan commented on src/pages/exam.tsx
> +      <QuestionsForm />
This component is not really needed

2023-05-19 20:28 UTC, Allislove commented on src/pages/exam.tsx
> +      <QuestionsForm />
Put all into the principal ?

2023-05-19 20:31 UTC, Allislove commented on src/components/questions.tsx
> +    // console.log(data);
All the useEffect? @Israel-Laguan

2023-05-19 20:31 UTC, Allislove commented on src/components/questions.tsx
> +          //console.log("Hello World!");
lines 28-29?

2023-05-19 21:15 UTC, Allislove commented
@Israel-Laguan  Can you review again please!

2023-05-23 13:02 UTC, Israel-Laguan commented on src/pages/exam.tsx
> +      <QuestionsForm />
In this case yes

2023-05-23 13:03 UTC, Israel-Laguan commented
Linter says that this file needs revision
![image](https://github.com/Israel-Laguan/theia-testing-app/assets/36519478/8f617b18-0540-4c33-9b80-0f69b82904a8)
Please update with linter

2023-05-23 18:19 UTC, Allislove commented
@Israel-Laguan Done, all checks have passed.

2023-05-23 19:33 UTC, Israel-Laguan commented on src/pages/exam.tsx
> +      console.log(loading, '*** 01 Loading ***')
Remove

2023-05-23 19:33 UTC, Israel-Laguan commented on src/pages/exam.tsx
> +    console.log(`${loading ? 'Loading...' : 'Get a JSON'};`)
Remove

2023-05-23 19:33 UTC, Israel-Laguan commented on src/styles/globals.css
> +  padding: 0 20px;
Remove the commented code if not used

2023-05-23 19:44 UTC, Allislove commented on src/pages/exam.tsx
> +      console.log(loading, '*** 01 Loading ***')
@Israel-Laguan  the console.log ?

2023-05-23 19:45 UTC, Allislove commented on src/pages/exam.tsx
> +    console.log(`${loading ? 'Loading...' : 'Get a JSON'};`)
Console.log ?

2023-05-23 19:53 UTC, Israel-Laguan commented on src/pages/exam.tsx
> +    console.log(`${loading ? 'Loading...' : 'Get a JSON'};`)
Yes, not needed

2023-05-23 19:53 UTC, Israel-Laguan commented on src/pages/exam.tsx
> +      console.log(loading, '*** 01 Loading ***')
yes

2023-05-23 20:16 UTC, Allislove commented
@Israel-Laguan  Done, can you review again plz

2023-05-23 20:28 UTC, Israel-Laguan approved these changes

2023-05-23 20:29 UTC, merged